name: Run tests and publish results on PRs

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.connectionString }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        working-directory: ./Backend
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        working-directory: ./Backend
        run: dotnet restore

      - name: Run Tests
        working-directory: ./Backend
        run: |
          mkdir -p test-results
          dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory ./test-results
        continue-on-error: true

      - name: Publish test results
        working-directory: ./Backend
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results/test-results.trx 